server.port: 8081

eureka:
  instance.hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url.defaultZone: http://localhost:8070/eureka

spring:
  cloud.gateway:
    default-filters:
      - TokenRelay=
      - RemoveRequestHeader=Cookie
    discovery.locator:
      enabled: true
      lower-case-service-id: true

  security.oauth2.client:
    provider:
      keycloak:
        issuer-uri: http://localhost:8080/realms/master
        user-name-attribute: preferred_username
    registration:
      keycloak:
        provider: keycloak
        client-id: uzum
        client-secret: 'Zw5qLnjk1kR8lUXSbiHi9rILAYILKJbi'
        authorization-grant-type: authorization_code
        redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        scope: openid
