spring:
  application.name: auth
  profiles.active: dev
  config.import: optional:configserver:http://localhost:8071


keycloak:
  auth-server-url: http://localhost:8080
  realm: master
  resource: uzum
  public-client: true
  use-resource-role-mappings: true